### ISSUE TITLE
Small icon blur fixing

### ISSUE THREAD

**Issue by syorito-hatsuki** [BlueMap-Minecraft/BlueMapVue#45]
In css for POI markers as optional settings  `image-rendering: pixelated;`
https://developer.chrome.com/blog/pixelated/

**Comment by TBlueF** [comment]
Please elaborate.
POI-Marker icons can not be resized, they are displayed in their native-resolution only, so there should be no reason to pixelate the icon?

**Comment by syorito-hatsuki** [comment]
Here video example
https://drive.google.com/file/d/1Pcb-ZupTvXW8lkXAuOLmABaJVaqHVMbp/view?usp=sharing

**Comment by TBlueF** [comment]
This is now possible using custom styles and css-classes on poi-markers (see newest API changes)
